Feature/form component
isdi-coders-2023/coding-adventure-Anna-Marrodan-front-202301-BCN pull request #2
Opened 2023-02-28 14:37 UTC by AnnaMaPe

Create Form component HTML
Merge master to local branch to obtain updated features

2023-02-28 15:01 UTC, mariogl requested changes

2023-02-28 15:01 UTC, mariogl commented on src/components/Form/Form.tsx
> +      <h2>Register for the event</h2>
El componente formulario sólo debería tener el formulario, el `<h>` formaría parte de la página.

2023-02-28 15:01 UTC, mariogl commented on src/components/Form/Form.tsx
> +          <span className="form__required-text">Email is required</span>
Este elemento `required-text` pertenece al bloque `form`, pero no existe ningún bloque `form` (hablo de nomenclatura BEM).

2023-02-28 15:04 UTC, AnnaMaPe commented on src/components/Form/Form.tsx
> +      <h2>Register for the event</h2>
Entendido!

2023-02-28 15:06 UTC, AnnaMaPe commented on src/components/Form/Form.tsx
> +          <span className="form__required-text">Email is required</span>
En este caso no indico register-form__required-text porque pensaba que poniendo solo form__required-text era más genérico en el caso de querer reusar el componente. 
Ahora aplico el BEM correcto.

2023-02-28 15:25 UTC, mariogl approved these changes
Siguiente fase: dale estilos al formulario (no dar estilo al input type file).

2023-02-28 15:45 UTC, AnnaMaPe commented
🥇 Add modificators to BEM in Form component and create FormProps 

@mariogl

2023-02-28 15:49 UTC, mariogl requested changes

2023-02-28 15:49 UTC, mariogl commented on src/components/Form/Form.tsx
> +          hidden
¿Por qué tiene un atributo `hidden` pero también un modificador `visible`?

2023-02-28 15:53 UTC, AnnaMaPe commented on src/components/Form/Form.tsx
> +          hidden
Entiendo que cuando el atributo está true, o sea se hidden, quiere decir que el elemento no está visible. Pero cuando está hidden es false entonces es visible. De aquí que el modificador sea visible y no hidden.

2023-02-28 16:00 UTC, mariogl commented on src/components/Form/Form.tsx
> +          hidden
El atributo no está a true ni a false (fíjate que no aparece ninguno de estos dos valores), es un atributo que o está o no está. Si está, significa que quieres que el span esté hidden, por lo tanto no tiene sentido que le pongas la clase visible.

2023-03-01 14:19 UTC, mariogl approved these changes

2023-03-01 14:23 UTC, merged